
project_id = "tygjlytzgbqfjqgculld"

[functions.save-secret]
verify_jwt = false

[functions.fetch-content]
verify_jwt = false

[functions.process-csv]
verify_jwt = false

[functions.ai-optimization]
verify_jwt = false

[functions.collect-analytics]
verify_jwt = false

[functions.publish-content]
verify_jwt = false

[functions.scheduler]
verify_jwt = false
