// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tygjlytzgbqfjqgculld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5Z2pseXR6Z2JxZmpxZ2N1bGxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODQyMTksImV4cCI6MjA2MzY2MDIxOX0.oYBZewuq9gtFx47KRVTFfD8Uo-FBtGkMf-p_Xm-WPWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);